
[project]
name = "diffusionpy"
version = "0.0.6"
authors = [
    {name = "Dominik Borrmann", email = "dominik.borrmann@tu-dortmund.de"},
]
description = "A package for describing diffusion in and out of liquids and amorphous substances"
readme = "README.md"
license = {text = "MIT"}

dependencies = [
    "numpy",
    "pandas",
    "pywin32",
    "casadi",
    "matplotlib",
    "xloil"
]
[build-system]
requires = [
  "setuptools >= 40.9.0",
  "wheel",
]
[tool.setuptools.packages.find]
include = ["diffusionpy"]