from __future__ import division, print_function, absolute_import

from .Stefan_Maxwell_segmental import Diffusion_MS,Diffusion1D
from .Stefan_Maxwell_segmental_xloil import Diffusion_MS_xloil,Diffusion1D_xloil